// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using NXCare.Domain.Entities.Base;
using NXCare.Domain.Interfaces.Entities;

namespace NXCare.Domain.Entities
{
    public partial class Speciality : BaseEntity, IBaseEntityWithDates<int>
    {
    }
}