// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace NXCare.Domain.Entities
{
    public partial class Address
    {
        public Address()
        {
            PatientAddress = new HashSet<PatientAddress>();
            PhysicianAddress = new HashSet<PhysicianAddress>();
        }

        public int Id { get; set; }
        public int CountryId { get; set; }
        public string PostalCode { get; set; }
        public string City { get; set; }
        public string Street { get; set; }
        public string Number { get; set; }
        public string Floor { get; set; }
        public DateTime CreatedOn { get; set; }
        public DateTime? ModifiedOn { get; set; }
        public DateTime? DeletedOn { get; set; }

        public virtual Country Country { get; set; }
        public virtual ICollection<PatientAddress> PatientAddress { get; set; }
        public virtual ICollection<PhysicianAddress> PhysicianAddress { get; set; }
    }
}