// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace NXCare.Domain.Entities
{
    public partial class Country
    {
        public Country()
        {
            Address = new HashSet<Address>();
            Patient = new HashSet<Patient>();
            Physician = new HashSet<Physician>();
        }

        public int Id { get; set; }
        public string Alpha2Code { get; set; }
        public string NameTranslationKey { get; set; }
        public string Alpha3Code { get; set; }
        public int NumericCode { get; set; }
        public int PhoneCode { get; set; }
        public DateTime CreatedOn { get; set; }
        public DateTime? ModifiedOn { get; set; }
        public DateTime? DeletedOn { get; set; }

        public virtual ICollection<Address> Address { get; set; }
        public virtual ICollection<Patient> Patient { get; set; }
        public virtual ICollection<Physician> Physician { get; set; }
    }
}