// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace NXCare.Domain.Entities
{
    public partial class Location
    {
        public int Id { get; set; }
        public Guid PublicId { get; set; }
        public int ServiceId { get; set; }
        public string Room { get; set; }
        public string Bed { get; set; }
        public DateTime CreatedOn { get; set; }
        public DateTime? ModifiedOn { get; set; }
        public DateTime? DeletedOn { get; set; }

        public virtual Service Service { get; set; }
    }
}