// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace NXCare.Domain.Entities
{
    public partial class Physician
    {
        public Physician()
        {
            PhysicianAddress = new HashSet<PhysicianAddress>();
            TransitionAdmittingPhysician = new HashSet<Transition>();
            TransitionAttendingPhysician = new HashSet<Transition>();
            TransitionConsultingPhysician = new HashSet<Transition>();
            TransitionReferringPhysician = new HashSet<Transition>();
            Visit = new HashSet<Visit>();
        }

        public int Id { get; set; }
        public Guid PublicId { get; set; }
        public string NationalId { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public string FirstName { get; set; }
        public DateTime? BirthDate { get; set; }
        public int? NationalityId { get; set; }
        public int? LanguageId { get; set; }
        public int? Sex { get; set; }
        public string MedicalLicenseId { get; set; }
        public int? SpecialityId { get; set; }
        public DateTime CreatedOn { get; set; }
        public DateTime? ModifiedOn { get; set; }
        public DateTime? DeletedOn { get; set; }
        public string ExternalId { get; set; }

        public virtual Language Language { get; set; }
        public virtual Country Nationality { get; set; }
        public virtual ICollection<PhysicianAddress> PhysicianAddress { get; set; }
        public virtual ICollection<Transition> TransitionAdmittingPhysician { get; set; }
        public virtual ICollection<Transition> TransitionAttendingPhysician { get; set; }
        public virtual ICollection<Transition> TransitionConsultingPhysician { get; set; }
        public virtual ICollection<Transition> TransitionReferringPhysician { get; set; }
        public virtual ICollection<Visit> Visit { get; set; }
    }
}