// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace NXCare.Domain.Entities
{
    public partial class Transition
    {
        public int Id { get; set; }
        public int VisitId { get; set; }
        public int LocationId { get; set; }
        public int? ReferringPhysicianId { get; set; }
        public int? AdmittingPhysicianId { get; set; }
        public int? AttendingPhysicianId { get; set; }
        public int? ConsultingPhysicianId { get; set; }
        public DateTime CreatedOn { get; set; }
        public DateTime? ModifiedOn { get; set; }
        public DateTime? DeletedOn { get; set; }

        public virtual Physician AdmittingPhysician { get; set; }
        public virtual Physician AttendingPhysician { get; set; }
        public virtual Physician ConsultingPhysician { get; set; }
        public virtual Physician ReferringPhysician { get; set; }
        public virtual Visit Visit { get; set; }
    }
}