// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace NXCare.Domain.Entities
{
    public partial class Visit
    {
        public Visit()
        {
            Transition = new HashSet<Transition>();
        }

        public int Id { get; set; }
        public Guid PublicId { get; set; }
        public string ExternalId { get; set; }
        public int AdmissionType { get; set; }
        public DateTime AdmissionDate { get; set; }
        public DateTime? DischargeDate { get; set; }
        public int AdmittingPhysicianId { get; set; }
        public DateTime CreatedOn { get; set; }
        public DateTime? ModifiedOn { get; set; }
        public DateTime? DeletedOn { get; set; }

        public virtual Physician AdmittingPhysician { get; set; }
        public virtual ICollection<Transition> Transition { get; set; }
    }
}